### ISSUE TITLE
Changing location of a big.gap when using a dataframe as input to create a chord diagram.

### ISSUE THREAD

**Issue by jdumdie** [jokergoo/circlize#164]
I am trying to create a chord diagram of curated ligand-receptor interactions using the chord.diagram function in the circlize package, using a dataframe as input. Since I want to color the chords by different parameters in my dataframe input, I chose this route instead of converting to a matrix. However, I would like all of the ligands (everything in the "from" column) on one side, separated by a big gap from all of the receptors (everything in the "to" column)..

Here is the head of my df:

```
       from       to   pearson
1 TE_ADAM15 PE_ITGA5 0.1265234
2 TE_ADAM15 PE_ITGB1 0.1265234
3 TE_ADAM17 PE_ITGA5 0.1791027
4 TE_ADAM17 PE_ITGB1 0.1791027
5  TE_ADAM9 PE_ITGA6 0.1846945
6  TE_ADAM9 PE_ITGAV 0.1846945
```
And here is the code I use:

```r
df = data.frame(from = INT$from, to = INT$to, pearson = INT$combined_pearson, stringsAsFactors = FALSE)
TE1 = grep("TE_", INT$from, value=TRUE)
TE2 = grep("TE_", INT$to, value=TRUE)
TE=union(TE1,TE2)
PE1 = grep("PE_", INT$from, value=TRUE)
PE2 = grep("PE_", INT$to, value=TRUE)
PE=union(PE1,PE2)
allIDs=union(INT$from, INT$to)
sorted<-sort(allIDs)

col_range = colorRamp2(breaks = range(df$pearson),
                     colors = c("gold","blue"),
                     transparency = 0)

circos.par(start.degree = 90)
chordDiagram(df, order=sorted, 
             scale = TRUE,
             directional = 1, diffHeight = uh(6, "mm"),
             big.gap = 40,
             col = col_range(df$pearson), grid.col = "black",
             transparency=0,
             annotationTrack = "grid",
             annotationTrackHeight =0.02,
             preAllocateTracks = list(list(track.height = 0.06),
                                      list(track.height = 0.1)))
highlight.sector(PE, track.index = 1, col = "orangered")
highlight.sector(TE, track.index = 1, col = "darkgreen")
```

However, what I am seeing is that the big.gap does not get placed in between the "from" and "to" values in all cases. Attached is an example. So my question is how to place the big gap in a specific location, using a dataframe to create a chord diagram. Any help would be so appreciated! 
![test](https://user-images.githubusercontent.com/28517050/80431494-6f364e00-88a6-11ea-9f6f-a5c63ea82caa.jpeg)

**Comment by jokergoo** [comment]
You are also using `order` and `scale` arguments here. I cannot imagine the behaviour of the function. Can you attach the object `INT` or `df` so that I can run line by line to check?

**Comment by jdumdie** [comment]
Thanks so much for your help. Attached is the input file I used.
[Blast_ZhouLi_EPItoPE-LR.txt](https://github.com/jokergoo/circlize/files/4575907/Blast_ZhouLi_EPItoPE-LR.txt)

**Comment by jokergoo** [comment]
Hi, sorry for the late reply. I tested with circlize 0.4.9 and it works fine. You can see the two highlighted tracks cover perfectly to the two groups.

Can you try with the newest version?

![image](https://user-images.githubusercontent.com/449218/82363920-d57a4080-9a0e-11ea-9cd2-07585631cd88.png)

**Comment by jdumdie** [comment]
Hello, thank you so much for looking in to this. I am using circlize 0.4.9. Does it also work for you using this input table?
[Blast_ZhouLi_TEtoPE-LR.txt](https://github.com/jokergoo/circlize/files/4669770/Blast_ZhouLi_TEtoPE-LR.txt)

**Comment by jokergoo** [comment]
Hi, this was a bug and now I have fixed. Please update from GitHub.

```r
devtools::install_github("jokergoo/circlize")
```

![image](https://user-images.githubusercontent.com/449218/82738308-fd331680-9d36-11ea-88dd-7ac44afbd763.png)

**Comment by jdumdie** [comment]
I just updated and it is still not working. The update ran just fine.

**Comment by jokergoo** [comment]
Following is the complete code that generates the plot that I have attached previously:

```r
INT = read.table("~/Downloads/Blast_ZhouLi_TEtoPE-LR.txt", header = TRUE)

df = data.frame(from = INT$from, to = INT$to, pearson = INT$combined_pearson, stringsAsFactors = FALSE)
TE1 = grep("TE_", INT$from, value=TRUE)
TE2 = grep("TE_", INT$to, value=TRUE)
TE=union(TE1,TE2)
PE1 = grep("PE_", INT$from, value=TRUE)
PE2 = grep("PE_", INT$to, value=TRUE)
PE=union(PE1,PE2)
allIDs=union(INT$from, INT$to)
sorted<-sort(allIDs)

col_range = colorRamp2(breaks = range(df$pearson),
                     colors = c("gold","blue"),
                     transparency = 0)

circos.par(start.degree = 90)
chordDiagram(df, order=sorted, 
             scale = TRUE,
             directional = 1, diffHeight = uh(6, "mm"),
             big.gap = 40,
             col = col_range(df$pearson), grid.col = "black",
             transparency=0,
             annotationTrack = "grid",
             annotationTrackHeight =0.02,
             preAllocateTracks = list(list(track.height = 0.06),
                                      list(track.height = 0.1)))
highlight.sector(PE, track.index = 1, col = "orangered")
highlight.sector(TE, track.index = 1, col = "darkgreen")
```

And this is my session info

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] circlize_0.4.10 colorout_1.2-2 

loaded via a namespace (and not attached):
[1] colorspace_1.4-1    compiler_4.0.0      GlobalOptions_0.1.1
[4] grid_4.0.0          shape_1.4.4        
```

**Comment by jdumdie** [comment]
Thank you so much! I guess I just needed to update my R to the newest version. I was using 3.6.0. Great package by the way! :)
